// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentInformationProject.Database;

#nullable disable

namespace StudentInformationProject.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentInformationProject.Models.DomainModels.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Classes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            ModificationDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            Name = "Class 1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            ModificationDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            Name = "Class 2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            ModificationDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            Name = "Class 3"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            ModificationDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            Name = "Class 4"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            ModificationDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            Name = "Class 5"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            ModificationDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            Name = "Class 6"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            ModificationDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            Name = "Class 7"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            ModificationDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            Name = "Class 8"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            ModificationDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            Name = "Class 9"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            ModificationDate = new DateTime(2024, 6, 3, 1, 59, 26, 87, DateTimeKind.Local).AddTicks(4018),
                            Name = "Class 10"
                        });
                });

            modelBuilder.Entity("StudentInformationProject.Models.DomainModels.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("StudentInformationProject.Models.DomainModels.Student", b =>
                {
                    b.HasOne("StudentInformationProject.Models.DomainModels.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("StudentInformationProject.Models.DomainModels.Class", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
